name: 1.20.1 - Forge - Runtime Test
on:
  workflow_run:
    workflows: ["1.20.1 - Forge - Build", "1.20.1 - Forge - Test"]
    types:
      - completed

jobs:
  runtime-test:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-runtime-test.yml@main
    with:
      project-root: .
      gradle-args: build
      cache-mc: github
      runs-on: HomeServ